// Generated by gencpp from file nbvplanner/nbvp_srv.msg
// DO NOT EDIT!


#ifndef NBVPLANNER_MESSAGE_NBVP_SRV_H
#define NBVPLANNER_MESSAGE_NBVP_SRV_H

#include <ros/service_traits.h>


#include <nbvplanner/nbvp_srvRequest.h>
#include <nbvplanner/nbvp_srvResponse.h>


namespace nbvplanner
{

struct nbvp_srv
{

typedef nbvp_srvRequest Request;
typedef nbvp_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct nbvp_srv
} // namespace nbvplanner


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::nbvplanner::nbvp_srv > {
  static const char* value()
  {
    return "0e9a67b6e01ddd6d303ae107f62349a1";
  }

  static const char* value(const ::nbvplanner::nbvp_srv&) { return value(); }
};

template<>
struct DataType< ::nbvplanner::nbvp_srv > {
  static const char* value()
  {
    return "nbvplanner/nbvp_srv";
  }

  static const char* value(const ::nbvplanner::nbvp_srv&) { return value(); }
};


// service_traits::MD5Sum< ::nbvplanner::nbvp_srvRequest> should match 
// service_traits::MD5Sum< ::nbvplanner::nbvp_srv > 
template<>
struct MD5Sum< ::nbvplanner::nbvp_srvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::nbvplanner::nbvp_srv >::value();
  }
  static const char* value(const ::nbvplanner::nbvp_srvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::nbvplanner::nbvp_srvRequest> should match 
// service_traits::DataType< ::nbvplanner::nbvp_srv > 
template<>
struct DataType< ::nbvplanner::nbvp_srvRequest>
{
  static const char* value()
  {
    return DataType< ::nbvplanner::nbvp_srv >::value();
  }
  static const char* value(const ::nbvplanner::nbvp_srvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::nbvplanner::nbvp_srvResponse> should match 
// service_traits::MD5Sum< ::nbvplanner::nbvp_srv > 
template<>
struct MD5Sum< ::nbvplanner::nbvp_srvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::nbvplanner::nbvp_srv >::value();
  }
  static const char* value(const ::nbvplanner::nbvp_srvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::nbvplanner::nbvp_srvResponse> should match 
// service_traits::DataType< ::nbvplanner::nbvp_srv > 
template<>
struct DataType< ::nbvplanner::nbvp_srvResponse>
{
  static const char* value()
  {
    return DataType< ::nbvplanner::nbvp_srv >::value();
  }
  static const char* value(const ::nbvplanner::nbvp_srvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NBVPLANNER_MESSAGE_NBVP_SRV_H
